#!/bin/sh

# Remove previous version of Google Chrome from /Applications

if [ -d "$3/Applications/Firefox.app" ]; then
   rm -rf "$3/Applications/Firefox.app"
fi

#Create files if they dont exist

if [ -d /Users/home/Library/Application\ Support/Firefox/Profiles/internetuser.default ]
then
	echo "Profile exists"
else
	mkdir -p /Users/home/Library/Application\ Support/Firefox/Profiles/internetuser.default
fi

if [ -f /Users/home/Library/Application\ Support/Firefox/profiles.ini ]
then
	echo "Profile.ini exists"
else
	
	mkdir -p /Users/home/Library/Application\ Support/Firefox/
	echo "[Profile0]
Name=internetuser.default
IsRelative=1
Path=Profiles/internetuser.default
" > /Users/home/Library/Application\ Support/Firefox/profiles.ini
	chmod -R a+rwx /Users/home/Library/Application\ Support/Firefox/
fi

