#!/bin/sh

# Remove previous version of Google Chrome from /Applications

if [ -d "$3/Applications/Firefox.app" ]; then
   rm -rf "$3/Applications/Firefox.app"
fi

#Create files if they dont exist

if [ -d /User/home/Library/Application\ Support/Firefox/Profiles/internetuser.default ]
then
	echo "Profile exists"
else
	mkdir -p /User/home/Library/Application\ Support/Firefox/Profiles/internetuser.default
fi

if [ -d /User/home/Library/Application\ Support/Firefox/profiles.ini ]
then
	echo "Profile.ini exists"
else
	echo  "[Profile0]
Name=internetuser.default
IsRelative=1
Path=Profiles/internetuser.default
" > /Library/Application\ Support/Firefox/profiles.ini
fi

